redis:
  image: redis:alpine
  restart: always
  hostname: redis
  ports:
    - "6379:6379"
  volumes:
    - redis_data:/data

app:
  build: .
  restart: always
  hostname: hitcounter
  ports:
    - "5000:5000"
  links:
    - redis
