apiVersion: serving.knative.dev/v1alpha1
kind: Service
metadata:
  name: lab-docker
  namespace: default
spec:
  runLatest:
    configuration:
      revisionTemplate:
        spec:
          container:
            image: __IMAGE__
